import { stringify } from 'yaml';

import type { ReportDocument } from './model.js';

const HEADER = `# reports/<id>/index.yaml — generated by @lab34/health
#
# Every datapoint the report shows is in this file. index.html embeds a
# verbatim copy of it and renders each section from it, so editing a value
# here and reloading the HTML changes the report.
#
# See docs/formats.md for the field reference.
`;

/**
 * Serialises the report document.
 *
 * Written with a wide line width and block strings so the file stays readable
 * and diffable: two consecutive reports should differ only where the data did.
 */
export function toYaml(document: ReportDocument): string {
  const body = stringify(document, {
    indent: 2,
    lineWidth: 0,
    defaultStringType: 'QUOTE_DOUBLE',
    defaultKeyType: 'PLAIN',
    nullStr: 'null',
    singleQuote: false,
  });
  return `${HEADER}${body}`;
}
